---------------------------- LEB NO:- 13 SP --------------------------
CREATE TABLE PERSON(
WHORKERID INT IDENTITY(1,1) PRIMARY KEY ,
FIRSTNAME VARCHAR(100) NOT NULL,
LASTNAME VARCHAR(100) NOT NULL,
SALARY DECIMAL(8,2) NOT NULL,
JOININGDATE DATETIME NOT NULL,
DEPARTMENTID INT FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT (DEPARTMENTID) NULL,
DESIGNATIONID INT FOREIGN KEY (DESIGNATIONID) REFERENCES DESIGNATION (DesignationID)NULL);

INSERT INTO PERSON VALUES(101, 'Rahul Anshu', 56000, '01-JAN-1990', 1, 12),
(102, 'Hardik Hinsu', 18000, '25-SEP-1990', 2, 11),
(103, 'Bhavin Kamani', 25000, '14-MAY-1991', NULL, 11),
(104, 'Bhoomi Patel', 39000, '20-FEB-2014', 1, 13),
(105, 'Rohit Rajgor', 17000, '23-JUL-1990', 2, 15),
(106, 'Priya Mehta', 25000, '18-OCT-1990', 2, NULL),
(107, 'Neha Trivedi', 18000, '20-FEB-2014', 3, 15);

CREATE TABLE DEPARTMENT(
DEPARTMENTID INT PRIMARY KEY,
DEPARTMENTNAME VARCHAR(100) NOT NULL UNIQUE);


INSERT INTO DEPARTMENT VALUES(
1, 'Admin'),
(2, 'IT'),
(3, 'HR'),
(4, 'Account'); 

CREATE TABLE Designation(
DesignationID Int Primary Key,
DesignationName Varchar(100) Not Null Unique);

INSERT INTO Designation VALUES(
11, 'Jobber'),
(12,'Welder'),
(13, 'Clerk'),
(14, 'Manager'),
(15, 'CEO');

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT
SELECT * FROM Designation
DROP TABLE PERSON
DROP TABLE DEPARTMENT
DROP TABLE Designation
--1 --
CREATE PROCEDURE SP_SEPARTMENT_IN
	@DEPARTMENTID INT,
	@DEPARTMENTNAME VARCHAR(100) 
	AS
	BEGIN
		INSERT INTO DEPARTMENT VALUES(@DEPARTMENTID , @DEPARTMENTNAME)		
	END 

EXEC SP_SEPARTMENT_IN 4, 'Account'


SELECT * FROM DEPARTMENT

CREATE PROCEDURE SP_DESIGNATION_IN
	@DesignationID INT,
	@DesignationName VARCHAR(100) 
	AS
	BEGIN
		INSERT INTO DESIGNATION  VALUES(@DesignationID ,	@DesignationName)		
	END 

	EXEC SP_DESIGNATION_IN 14, 'Manager'
SELECT * FROM DESIGNATION

CREATE OR ALTER PROCEDURE SP_PERSON2_INSERT
	
	@FIRSTNAME VARCHAR(100), 
	@LASTNAME VARCHAR(100),
	@SALARY DECIMAL(8,2),
	@JOININGDATE DATETIME,
	@DEPARTMENTID INT,
	@DESIGNATIONID INT

AS
BEGIN
	INSERT INTO PERSON VALUES(@FIRSTNAME,@LASTNAME,@SALARY,@JOININGDATE,@DEPARTMENTID,@DESIGNATIONID);
END

EXEC SP_PERSON2_INSERT 
105, 'Rohit Rajgor', 17000, '23-JUL-1990', 2, 15   -- RECODE 105 INSERT KARTI VAKHATE ERROR AAVE 
(106, 'Priya Mehta', 25000, '18-OCT-1990', 2, NULL),
(107, 'Neha Trivedi', 18000, '20-FEB-2014', 3, 15
SELECT * FROM PERSON








